### ISSUE TITLE
API does not prompt for actions

### ISSUE THREAD

**Issue by Rinzlers** [iantoon0/5E-BattleMaster#2]
For reference, the error message generated was: TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at TurnChange (apiscript.js:327:53)
    at apiscript.js:945:17
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:146:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:146:1), <anonymous>:70:8)
    at TrackedObj.set (/home/node/d20-api-server/api.js:901:14)
    at updateLocalCache (/home/node/d20-api-server/api.js:1194:18)
    at /home/node/d20-api-server/api.js:1484:7
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560
    at hc (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:39:147)
    at Kd (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:546)

**Comment by gkmk** [comment]
Have forked this project and fixed some of these bugs
You may try out v0.3
https://github.com/gkmk/5E-BattleMaster
